name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - test  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - test  # Запускать при создании pull request в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Build project
        run: | 
          cd src
          make
         

  package:
    needs: build  # Запускать только после успешного выполнения build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install stuff
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper
          sudo apt install -y build-essential cmake

      - name: Create .deb package
        run: |
          dpkg-deb --build usr/bin

