name: C++ CI/CD Pipeline

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании pull request в ветку main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - name: Build project
        run: | 
          cd src
          make
         
      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: devproj9exe
          path: ./usr/bin

      - name: Upload testfile as artifact
        uses: actions/upload-artifact@v4
        with:
          name: testexe
          path: ./cicd

  test:
    needs: build
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Download test artifact
        uses: actions/download-artifact@v4
        with:
          name: testexe
          path: ./cicd

      - name: Run tests
        run: |
          sudo chmod 755 cicd/testexe
          ./cicd/testexe

  package:
    needs: test  # Запускать только после успешного выполнения build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: devproj9exe
          path: ./usr/bin

      - name: Install stuff
        run: |
          sudo apt update
          sudo apt install -y devscripts debhelper

      - name: Create .deb package # build right here and rename
        run: |
          dpkg-deb --build . 
          mv ..deb package.deb

      - name: Upload .deb package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package.deb
          path: ./

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: package.deb
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t genkted/3lab:latest .
      - name: Run Docker container for testing
        run: |
          docker run --rm genkted/3lab:latest ./3lab/usr/bin/devproj9exe
      - name: Push Docker image
        run: |
          docker push genkted/3lab:latest
